/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reports;

import conf.month;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;
import conf.dbconnect;
import Menu.menu;

/**
 *
 * @author User
 */
public class report extends javax.swing.JFrame {

    /**
     * Creates new form report
     */
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    
    public report() {
        initComponents();
        con = dbconnect.connection();
        //rtable.setVisible(false);
        rtable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,16));
        rtable.getTableHeader().setOpaque(true);
        rtable.getTableHeader().setBackground(new Color(255,255,255));
        rtable.getTableHeader().setForeground(new Color(0,102,255));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        sel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1500, 950));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 2, 1, 2, new java.awt.Color(0, 102, 204)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 950));
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/icons8-report-file-64.png"))); // NOI18N
        jLabel1.setText("Activity Report");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/icons8-go-back-64.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        sel.setBackground(new java.awt.Color(0, 51, 255));
        sel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sel.setForeground(new java.awt.Color(255, 255, 255));
        sel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March ", "April", "May", "June ", "July ", "August ", "September", "October ", "November", "December", " " }));
        sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("select a month");

        generate.setBackground(new java.awt.Color(0, 153, 204));
        generate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/icons8-newtonsoft-30.png"))); // NOI18N
        generate.setText("Generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        rtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204), 2));
        rtable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rtable.setForeground(new java.awt.Color(0, 102, 153));
        rtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rtable.setGridColor(new java.awt.Color(0, 153, 204));
        rtable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        rtable.setRowHeight(32);
        rtable.setSelectionBackground(new java.awt.Color(102, 51, 255));
        rtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(rtable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(456, 456, 456))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(back))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)))
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1124, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        menu Menu =new menu();
        setVisible(false);
        Menu.setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_selActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        // TODO add your handling code here:
        //month M =new month();
        int val = sel.getSelectedIndex();
        System.out.println(val);
         try
        {
            stmt = con.createStatement();
            
                
           if (val==0){
                String query = "SELECT * FROM report Where Month ='January'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            
            }else if (val==1){
                String query = "SELECT * FROM report Where Month ='February'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==2){
                String query = "SELECT * FROM report Where Month ='March'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==3){
                String query = "SELECT * FROM report Where Month ='April'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==4){
                 String query = "SELECT * FROM report Where Month ='May'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));   
            }else if (val==5){
                String query = "SELECT * FROM report Where Month ='June'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==6){
                String query = "SELECT * FROM report Where Month ='July'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==7){
                String query = "SELECT * FROM report Where Month ='August'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
             }else if (val==8){
                 String query = "SELECT * FROM report Where Month ='September'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==9){
                String query = "SELECT * FROM report Where Month ='October'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else if (val==10){
                String query = "SELECT * FROM report Where Month ='November'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }else{
                String query = "SELECT * FROM report Where Month ='December'";
                ResultSet re = stmt.executeQuery(query);
                rtable.setModel(DbUtils.resultSetToTableModel(re));
            }
           
            
            
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rtable;
    private javax.swing.JComboBox<String> sel;
    // End of variables declaration//GEN-END:variables
}
